### ISSUE TITLE
"api-server did not start"

### ISSUE THREAD

**Issue by lamoni** [Juniper/contrail-installer#116]
Using the latest, I'm having issues with the "api-server" not starting.

2016-02-27 13:29:20 Waiting for api-server to start...
lamoni@ubuntu:~/contrail-installer$ 2016-02-27 13:32:20 api-server did not start
2016-02-27 13:32:20 ++ echo 'api-server did not start'
2016-02-27 13:32:20 exited with status :1
2016-02-27 13:32:20 ++ exit 1
2016-02-27 13:32:20 ++ clean
2016-02-27 13:32:20 ++ local r=1
2016-02-27 13:32:20 ++ echo 'exited with status :1'
2016-02-27 13:32:20 ++ exit 1

Any suggestions on how to troubleshoot this?  I'm following the README exactly for trying to use this.

**Comment by lamoni** [comment]
I was able to hack my way around this by hard-coding the contrail-installer directory in the contrail.sh call:

 screen_it apiSrv "$(which contrail-api) --conf_file /etc/contrail/contrail-api.conf $RESET_CONFIG $RABBIT_OPTS"

No idea why, but it seems to be adding a rogue single-quote into the file path, which is odd, as it seems the same code is used to calculate the file paths for all the other screen_it calls.

**Comment by dsetia** [comment]
You can connect to contrail screen to find out if any dependent task is failing … that could also explain API server no starting. Lately zookeeper was having issue do to version number changes in the repository. This has been fixed.

—
Deepinder

**Comment by ajithadapa** [comment]
```
ipi@ipi:~/LAB/contrail-installer$ /usr/local/bin/contrail-api --conf_file /etc/contrail/contrail-api.conf --reset_config --rabbit_user rabbitcontrail --rabbit_password contrail123 --rabbit_server 127.0.0.1 & echo $! >/home/ipi/LAB/contrail-installer/status/contrail/apiSrv.pid; fg || echo "apiSrv failed to start" | tee "/home/ipi/LAB/contrail-installer/status/contrail/apiSrv.failure"
[1] 14492
/usr/local/bin/contrail-api --conf_file /etc/contrail/contrail-api.conf --reset_config --rabbit_user rabbitcontrail --rabbit_password contrail123 --rabbit_server 127.0.0.1
03/01/2016 04:05:02 PM [contrail-api]: SANDESH: CONNECT TO COLLECTOR: True
INFO:contrail-api:SANDESH: CONNECT TO COLLECTOR: True
03/01/2016 04:05:02 PM [contrail-api]: SANDESH: Logging: LEVEL: [SYS_INFO] -> [SYS_NOTICE]
INFO:contrail-api:SANDESH: Logging: LEVEL: [SYS_INFO] -> [SYS_NOTICE]
ERROR:contrail-api:SANDESH: [DROP: NoSession] __default__ [SYS_NOTICE]: VncApiError: Connecting to ifmap on 127.0.0.1:8443 as api-server
ERROR:contrail-api:Unable to open HTTP Port 8084, [Errno 98] Address already in use
```

**Comment by lamoni** [comment]
Seems to be fixed with latest commits

**Comment by AbdulMMalik** [comment]
I am still getting same error **unable to start api server**.

**Comment by saurumesh** [comment]
Hi AbdulMalik206267, did you get this resolve, If yes kindly help me in the same
